### PR TITLE
Clojars deployment

### PR DESCRIPTION
**Pull request by kelvinqian00**

### CODE REVIEW

**Comment by milt** [comment]
This looks a little less trivial than the other Clojars deployment PRs, just curious about the reasons for shuffling around the stuff in deps.edn (I'm sure there are good ones, just curious)

**Comment by kelvinqian00** [comment]
The gentests are dependent on Datasim, which itself relies on Pan. As you probably know, updating Pan on DS has been far more complicated than expected, so that process may still take a while.

**Review by milt — APPROVED** [review]
Looks good to me, thanks for the explanation

**Comment by kelvinqian00** [comment]
It seems like it'll only be a matter of time before Datasim itself is updated, though, so I'll wait until that happens then revert these temporary changes.

**Pull request merged**
